export const VENUES = [
  { code: '01', name: '桐生', pref: '群馬', slug: 'kiryu' },
  { code: '02', name: '戸田', pref: '埼玉', slug: 'toda' },
  { code: '03', name: '江戸川', pref: '東京', slug: 'edogawa' },
  { code: '04', name: '平和島', pref: '東京', slug: 'heiwajima' },
  { code: '05', name: '多摩川', pref: '東京', slug: 'tamagawa' },
  { code: '06', name: '浜名湖', pref: '静岡', slug: 'hamanako' },
  { code: '07', name: '蒲郡', pref: '愛知', slug: 'gamagori' },
  { code: '08', name: '常滑', pref: '愛知', slug: 'tokoname' },
  { code: '09', name: '津', pref: '三重', slug: 'tsu' },
  { code: '10', name: '三国', pref: '福井', slug: 'mikuni' },
  { code: '11', name: 'びわこ', pref: '滋賀', slug: 'biwako' },
  { code: '12', name: '住之江', pref: '大阪', slug: 'suminoe' },
  { code: '13', name: '尼崎', pref: '兵庫', slug: 'amagasaki' },
  { code: '14', name: '鳴門', pref: '徳島', slug: 'naruto' },
  { code: '15', name: '丸亀', pref: '香川', slug: 'marugame' },
  { code: '16', name: '児島', pref: '岡山', slug: 'kojima' },
  { code: '17', name: '宮島', pref: '広島', slug: 'miyajima' },
  { code: '18', name: '徳山', pref: '山口', slug: 'tokuyama' },
  { code: '19', name: '下関', pref: '山口', slug: 'shimonoseki' },
  { code: '20', name: '若松', pref: '福岡', slug: 'wakamatsu' },
  { code: '21', name: '芦屋', pref: '福岡', slug: 'ashiya' },
  { code: '22', name: '福岡', pref: '福岡', slug: 'fukuoka' },
  { code: '23', name: '唐津', pref: '佐賀', slug: 'karatsu' },
  { code: '24', name: '大村', pref: '長崎', slug: 'omura' },
]

export const VENUE_DATA: Record<string, { note: string; in1Rate: number }> = {
  '桐生': { note: '赤城おろしの強風。インが弱い難水面', in1Rate: 47 },
  '戸田': { note: '幅が狭く差し・まくり差しが有効', in1Rate: 50 },
  '江戸川': { note: '潮の満ち引きで水面が変化する難水面', in1Rate: 45 },
  '平和島': { note: '海水面で風の影響大。荒れやすい', in1Rate: 50 },
  '多摩川': { note: '河川水面で比較的インが強い', in1Rate: 54 },
  '浜名湖': { note: '広大な湖。風が強くインが弱くなりやすい', in1Rate: 51 },
  '蒲郡': { note: '穏やかな水面。インが強い。堅いレース多い', in1Rate: 58 },
  '常滑': { note: '海水面。インそこそこ強い', in1Rate: 55 },
  '津': { note: '海水面。水位変化あり。インの逃げが強い', in1Rate: 56 },
  '三国': { note: '冬は強風多い。海水面でうねりあり', in1Rate: 50 },
  'びわこ': { note: '比叡おろしの強風。インが弱くなりやすい', in1Rate: 48 },
  '住之江': { note: '静水プール。インが圧倒的に強い', in1Rate: 60 },
  '尼崎': { note: 'プール水面に近い。インが非常に強い', in1Rate: 59 },
  '鳴門': { note: '潮の流れが強い難水面', in1Rate: 48 },
  '丸亀': { note: '海水面。潮の影響あり', in1Rate: 54 },
  '児島': { note: '海水面。風が強いと荒れやすい', in1Rate: 52 },
  '宮島': { note: '海水面。潮の干満あり', in1Rate: 53 },
  '徳山': { note: '比較的穏やか。インが強い', in1Rate: 56 },
  '下関': { note: '潮流あり。インはやや強い', in1Rate: 54 },
  '若松': { note: '洞海湾内。インが強め', in1Rate: 57 },
  '芦屋': { note: '砂浜水面で荒れやすい。インは弱い', in1Rate: 49 },
  '福岡': { note: '博多湾内。波風の影響あり', in1Rate: 53 },
  '唐津': { note: '海水面。風の影響大', in1Rate: 51 },
  '大村': { note: '大村湾。穏やか。インが最強クラス', in1Rate: 62 },
}

export const LANE_COLORS = [
  { bg: '#00d4ff', text: '#04080d' },
  { bg: '#1a1a1a', text: '#ffffff' },
  { bg: '#cc2233', text: '#ffffff' },
  { bg: '#2255cc', text: '#ffffff' },
  { bg: '#e8e8e8', text: '#222222' },
  { bg: '#1a9944', text: '#ffffff' },
]